import pyautogui
import time
import random
import pyperclip
quotes = [
    "If you win, you live. If you lose, you die. If you don’t fight, you can’t win. - Eren Yeager",
    "The world is merciless, and it’s also very beautiful. - Mikasa Ackerman",
    "A lesson without pain is meaningless. That’s because you can’t gain something without sacrificing something in return. - Edward Elric",
    "The only thing we’re allowed to do is to believe that we won’t regret the choice we made. - Levi Ackerman",
    "Chaos isn’t a pit. Chaos is a ladder. - Petyr Baelish",
    "When you play the game of thrones, you win or you die. - Cersei Lannister",
    "The things I do for love. - Jaime Lannister",
    "A lion doesn’t concern itself with the opinion of sheep. - Tywin Lannister",
    "Winter is coming. - Ned Stark",
    "The night is dark and full of terrors. - Melisandre",
    "Fear cuts deeper than swords. - Arya Stark",
    "Power resides where men believe it resides. - Varys",
    "The world is full of monsters with friendly faces. - Reiner Braun",
    "The only true fear is fear itself. - Hange Zoë",
    "You should enjoy the little things in life, for one day you may look back and realize they were the big things. - Kurt Vonnegut",
    "The freedom to make decisions is the freedom to make mistakes. - Armin Arlert",
    "Every flight begins with a fall. - Hange Zoë",
    "A mind needs books as a sword needs a whetstone. - Tyrion Lannister",
    "When you tear out a man’s tongue, you are not proving him a liar, you’re only telling the world that you fear what he might say. - Tyrion Lannister",
    "The good ones always die young. - Sasha Blouse",
    "I want to see and understand the world outside. - Historia Reiss",
    "A girl is Arya Stark of Winterfell. And I’m going home. - Arya Stark",
    "There is only one war that matters—the Great War. And it is here. - Jon Snow",
    "A reader lives a thousand lives before he dies. The man who never reads lives only one. - Jojen Reed",
    "People die when they are killed. - Eren Yeager",
    "You cannot hope to bribe or twist... thank God! I’ve paid my debts. - Tyrion Lannister",
    "There’s always another secret. - Vin",
    "Don’t be ashamed of who you are. - Kelsier",
    "Sometimes the prize is not worth the costs. - Sazed",
    "I promise you, the world is changing. And the things we fear most may be what save us. - Vin",
    "The most important step a man can take is always the next one. - Kelsier",
    "You should never be ashamed of what you truly are. - Kelsier",
    "The only real freedom you have is the freedom to make mistakes. - Sazed",
    "You want to know what’s wrong with the world? Everyone lies. - Vin",
    "We’re all broken in some way. The question is what you do with the pieces. - Vin",
    "Sometimes, you have to do what’s right, not what’s easy. - Kelsier",
    "True strength is found in the moments when you want to give up but you keep going anyway. - Vin",
    "There is always hope. You just have to find it. - Sazed",
    "Faith isn’t about knowing. It’s about believing. - Sazed",
    "The best lies are those that contain a grain of truth. - Kelsier",
    "Power comes at a cost, and you must be willing to pay the price. - Vin",
    "In this world, everyone wears a mask. - Klein Moretti",
    "Secrets are the currency of power. - Klein Moretti",
    "The world hides many truths, but it always reveals itself to those who seek. - Klein Moretti",
    "Knowledge is the key to survival in the shadows. - Sherlock",
    "Sometimes the truth is more terrifying than any lie. - Klein Moretti",
    "Destiny is not set in stone; it is carved by the choices we make. - Klein Moretti",
    "In the game of secrets, trust is the rarest treasure. - Klein Moretti",
    "Power is meaningless without control. - Klein Moretti",
    "Even the smallest actions can change the course of fate. - Klein Moretti",
    "When you walk through darkness, be the light that guides your way. - Klein Moretti",
    "We are but pawns in a greater game, but pawns with the power to change the board. - Klein Moretti",
    "Hope is a fragile thing, but it is all we have sometimes. - Klein Moretti",
    "The past is a shadow that stretches long, but it cannot dictate your future. - Klein Moretti",
    "No one escapes the consequences of their choices, but some learn faster than others. - Klein Moretti",
    "Fear is a tool; wield it wisely or be consumed by it. - Klein Moretti",
    "The road to truth is paved with illusions and lies. - Klein Moretti",
    "In silence, the loudest secrets are kept. - Klein Moretti",
    "True power comes not from what you control, but from what you understand. - Klein Moretti",
    "To survive in the mist, one must learn to embrace the unknown. - Klein Moretti",
    "The eyes may see, but the soul perceives. - Klein Moretti",
    "The future is built on the dreams we dare to dream. - Kenji Endo",
    "Sometimes the truth hides behind the biggest lies. - Friend",
    "We all have our roles to play, no matter how small. - Maruo",
    "The past is a mystery we must unravel to save tomorrow. - Kenji Endo",
    "Friendship is the strongest weapon we have against the darkness. - Kenji Endo",
    "Sometimes to save the world, we have to lose ourselves first. - Kenji Endo",
    "Even the smallest actions can echo through time. - Friend",
    "Hope is a fragile thing, but it keeps us moving forward. - Maruo",
    "In the end, the real enemy is fear itself. - Kenji Endo",
    "The fate of many rests in the hands of the few who dare to fight. - Friend",
    "You were born to be a sacrifice. - Griffith",
    "Dreams are like the wind; they cannot be held, but they carry us forward. - Guts",
    "The only thing we're allowed to do is to believe that we won’t regret the choice we made. - Guts",
    "Struggle is what makes life worth living. - Guts",
    "In this world, the weak are meat, and the strong eat. - Griffith",
    "Sometimes, the hardest battles are the ones within ourselves. - Casca",
    "Fate is cruel, but we are crueler. - Guts",
    "Revenge is the sweetest pleasure that follows pain. - Guts",
    "I have no dreams anymore. No hopes, no plans. I live for the moment. - Guts",
    "The world is full of evil, but it’s up to us to fight it. - Guts",
    "A single person can change the course of history. - Kenji Endo",
    "Sometimes the greatest monsters are the people we trust. - Friend",
    "To protect what you love, you must first understand your own fears. - Maruo",
    "The world isn’t saved by heroes, but by those who refuse to give up. - Kenji Endo",
    "Memories can be both a curse and a blessing. - Friend",
    "Every generation has its own battles to fight. - Kenji Endo",
    "The truth is a double-edged sword; it can free or destroy. - Maruo",
    "Friendship and hope can light even the darkest paths. - Kenji Endo",
    "We fight because the future depends on us. - Friend",
    "Sometimes you must lose yourself to find the real truth. - Kenji Endo",
    "What is broken can be reforged stronger than before. - Guts",
    "The pain of loss is the price of love. - Casca",
    "Hatred is a fire that burns within, fueling strength and despair alike. - Guts",
    "In the end, all we have are the choices we make. - Griffith",
    "Even in darkness, the human spirit can find its way. - Guts",
    "The scars we carry tell the story of our survival. - Guts",
    "To live is to fight, to fight is to survive. - Guts",
    "True strength is standing despite the pain. - Casca",
    "Destiny is cruel, but so am I. - Guts",
    "In a world without mercy, kindness is rebellion. - Guts"

]


time.sleep(2)  # Time to click on Discord

while True:
    quote = random.choice(quotes)
    message = ">>> " + quote       # Add >>> before the quote
    pyperclip.copy(message)        # Copy modified message to clipboard
    pyautogui.hotkey('ctrl', 'v')  # Paste instantly
    pyautogui.press('enter')       # Send message
    time.sleep(2)

